name = "EEEAntennaLab"
uuid = "8c77593e-871c-4bf4-a215-59cbcab0de07"
authors = ["mtamer00 <merttamerkisisel@gmail.com> and contributors"]
version = "1.0.1-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
